//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccione
    {
        public int id { get; set; }
        public string direccion { get; set; }
        public int Persona_dni { get; set; }
        public int Localidad_id { get; set; }
    
        public virtual Localidade Localidade { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
