//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formulario
    {
        public Formulario()
        {
            this.Perfiles = new HashSet<Perfile>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string nombredemuestra { get; set; }
        public int Modulo_id { get; set; }
    
        public virtual Modulo Modulo { get; set; }
        public virtual ICollection<Perfile> Perfiles { get; set; }
    }
}
