//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WASSTDEntities : DbContext
    {
        public WASSTDEntities()
            : base("name=WASSTDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detalles_Tramites> Detalles_Tramites { get; set; }
        public virtual DbSet<Direccione> Direcciones { get; set; }
        public virtual DbSet<Estado> Estados { get; set; }
        public virtual DbSet<Formulario> Formularios { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<Localidade> Localidades { get; set; }
        public virtual DbSet<Modulo> Modulos { get; set; }
        public virtual DbSet<Perfile> Perfiles { get; set; }
        public virtual DbSet<Permiso> Permisos { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<Tipos_Documentos> Tipos_Documentos { get; set; }
        public virtual DbSet<Tipos_Personas> Tipos_Personas { get; set; }
        public virtual DbSet<Tipos_Tramites> Tipos_Tramites { get; set; }
        public virtual DbSet<Tramite> Tramites { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
