//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Direcciones = new HashSet<Direccione>();
            this.Tramites = new HashSet<Tramite>();
        }
    
        public int dni { get; set; }
        public string nombre_apellido { get; set; }
        public string sexo { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string email1 { get; set; }
        public string observaciones { get; set; }
        public string clave_fiscal { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public int Tipo_PersonaId { get; set; }
        public int Tipo_Documento_id { get; set; }
        public int Estado_id { get; set; }
    
        public virtual ICollection<Direccione> Direcciones { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Tipos_Documentos Tipos_Documentos { get; set; }
        public virtual Tipos_Personas Tipos_Personas { get; set; }
        public virtual ICollection<Tramite> Tramites { get; set; }
    }
}
