//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos_Tramites
    {
        public Tipos_Tramites()
        {
            this.Tramites = new HashSet<Tramite>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Tramite> Tramites { get; set; }
    }
}
