//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidades
    {
        public Localidades()
        {
            this.Direcciones = new HashSet<Direcciones>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int cp { get; set; }
        public int Provincia_id { get; set; }
    
        public virtual ICollection<Direcciones> Direcciones { get; set; }
        public virtual Provincias Provincias { get; set; }
    }
}
