//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Grupos = new HashSet<Grupos>();
        }
    
        public int id { get; set; }
        public string nombre_apellido { get; set; }
        public string clave { get; set; }
        public string email { get; set; }
        public bool estado { get; set; }
        public string usuario { get; set; }
    
        public virtual ICollection<Grupos> Grupos { get; set; }
    }
}
