//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WASSTDEntities : DbContext
    {
        public WASSTDEntities()
            : base("name=WASSTDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Detalles_Tramites> Detalles_Tramites { get; set; }
        public DbSet<Direcciones> Direcciones { get; set; }
        public DbSet<Estados> Estados { get; set; }
        public DbSet<Formularios> Formularios { get; set; }
        public DbSet<Grupos> Grupos { get; set; }
        public DbSet<Localidades> Localidades { get; set; }
        public DbSet<Modulos> Modulos { get; set; }
        public DbSet<Perfiles> Perfiles { get; set; }
        public DbSet<Permisos> Permisos { get; set; }
        public DbSet<Personas> Personas { get; set; }
        public DbSet<Provincias> Provincias { get; set; }
        public DbSet<Tipos_Documentos> Tipos_Documentos { get; set; }
        public DbSet<Tipos_Personass> Tipos_Personass { get; set; }
        public DbSet<Tipos_Tramites> Tipos_Tramites { get; set; }
        public DbSet<Tramites> Tramites { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
