//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfiles
    {
        public int id { get; set; }
        public int Grupo_id { get; set; }
        public int Permiso_id { get; set; }
        public int Formulario_id { get; set; }
    
        public virtual Formularios Formularios { get; set; }
        public virtual Grupos Grupos { get; set; }
        public virtual Permisos Permisos { get; set; }
    }
}
