//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public Personas()
        {
            this.Direcciones = new HashSet<Direcciones>();
            this.Tramites = new HashSet<Tramites>();
        }
    
        public int dni { get; set; }
        public string nombre_apellido { get; set; }
        public string sexo { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string email1 { get; set; }
        public string observaciones { get; set; }
        public string clave_fiscal { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public int Tipo_PersonaId { get; set; }
        public int Tipo_Documento_id { get; set; }
        public int Estado_id { get; set; }
    
        public virtual ICollection<Direcciones> Direcciones { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Tipos_Documentos Tipos_Documentos { get; set; }
        public virtual Tipos_Personass Tipos_Personass { get; set; }
        public virtual ICollection<Tramites> Tramites { get; set; }
    }
}
