//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tramites
    {
        public Tramites()
        {
            this.Detalles_Tramites = new HashSet<Detalles_Tramites>();
        }
    
        public int Id { get; set; }
        public int Tipo_Tramite_id { get; set; }
        public int Estado_id { get; set; }
        public int Persona_dni { get; set; }
    
        public virtual ICollection<Detalles_Tramites> Detalles_Tramites { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual Tipos_Tramites Tipos_Tramites { get; set; }
    }
}
